/* AUTO-GENERATED from packages/shared/src/theme/tokens.ts.
 * Do not edit by hand — run `npm run theme:generate -w packages/shared`. */

import type { AccentId, ColorTokens } from "./theme/tokens";

export const lightTokensRgb: ColorTokens = {
  background: "#fcfdfaff",
  foreground: "#15170eff",
  card: "#fcfdfaff",
  cardForeground: "#15170eff",
  popover: "#fefffcff",
  popoverForeground: "#15170eff",
  primary: "#2b301cff",
  primaryForeground: "#f8f9f5ff",
  secondary: "#e6eaddff",
  secondaryForeground: "#191c12ff",
  muted: "#f1f3ebff",
  mutedForeground: "#5c5f53ff",
  accent: "#dfe4d4ff",
  accentForeground: "#191c12ff",
  destructive: "#e7000bff",
  border: "#d9dcd2ff",
  input: "#d9dcd2ff",
  ring: "#6a7a31ff",
};

export const darkTokensRgb: ColorTokens = {
  background: "#0f1009ff",
  foreground: "#f1f2efff",
  card: "#191c12ff",
  cardForeground: "#f1f2efff",
  popover: "#191c12ff",
  popoverForeground: "#f1f2efff",
  primary: "#d5dacbff",
  primaryForeground: "#191c12ff",
  secondary: "#2c3022ff",
  secondaryForeground: "#f1f2efff",
  muted: "#23251cff",
  mutedForeground: "#969a8dff",
  accent: "#313524ff",
  accentForeground: "#f1f2efff",
  destructive: "#ff6467ff",
  border: "#ffffff1a",
  input: "#ffffff26",
  ring: "#798848ff",
};

export const accentPalettesRgb: Record<AccentId, { light: ColorTokens; dark: ColorTokens }> = {
  "olive": {
    "light": {
      "background": "#fcfdfaff",
      "foreground": "#15170eff",
      "card": "#fcfdfaff",
      "cardForeground": "#15170eff",
      "popover": "#fefffcff",
      "popoverForeground": "#15170eff",
      "primary": "#2b301cff",
      "primaryForeground": "#f8f9f5ff",
      "secondary": "#e6eaddff",
      "secondaryForeground": "#191c12ff",
      "muted": "#f1f3ebff",
      "mutedForeground": "#5c5f53ff",
      "accent": "#dfe4d4ff",
      "accentForeground": "#191c12ff",
      "destructive": "#e7000bff",
      "border": "#d9dcd2ff",
      "input": "#d9dcd2ff",
      "ring": "#6a7a31ff"
    },
    "dark": {
      "background": "#0f1009ff",
      "foreground": "#f1f2efff",
      "card": "#191c12ff",
      "cardForeground": "#f1f2efff",
      "popover": "#191c12ff",
      "popoverForeground": "#f1f2efff",
      "primary": "#d5dacbff",
      "primaryForeground": "#191c12ff",
      "secondary": "#2c3022ff",
      "secondaryForeground": "#f1f2efff",
      "muted": "#23251cff",
      "mutedForeground": "#969a8dff",
      "accent": "#313524ff",
      "accentForeground": "#f1f2efff",
      "destructive": "#ff6467ff",
      "border": "#ffffff1a",
      "input": "#ffffff26",
      "ring": "#798848ff"
    }
  },
  "green": {
    "light": {
      "background": "#fbfdfbff",
      "foreground": "#101812ff",
      "card": "#fbfdfbff",
      "cardForeground": "#101812ff",
      "popover": "#fdfffdff",
      "popoverForeground": "#101812ff",
      "primary": "#213324ff",
      "primaryForeground": "#f6f9f7ff",
      "secondary": "#e0ebe2ff",
      "secondaryForeground": "#141d16ff",
      "muted": "#edf4eeff",
      "mutedForeground": "#566158ff",
      "accent": "#d8e6daff",
      "accentForeground": "#141d16ff",
      "destructive": "#e7000bff",
      "border": "#d5ddd6ff",
      "input": "#d5ddd6ff",
      "ring": "#428252ff"
    },
    "dark": {
      "background": "#0b110cff",
      "foreground": "#eff3f0ff",
      "card": "#151d16ff",
      "cardForeground": "#eff3f0ff",
      "popover": "#151d16ff",
      "popoverForeground": "#eff3f0ff",
      "primary": "#cfdbd1ff",
      "primaryForeground": "#141d16ff",
      "secondary": "#253127ff",
      "secondaryForeground": "#eff3f0ff",
      "muted": "#1e271fff",
      "mutedForeground": "#909c92ff",
      "accent": "#28372bff",
      "accentForeground": "#eff3f0ff",
      "destructive": "#ff6467ff",
      "border": "#ffffff1a",
      "input": "#ffffff26",
      "ring": "#578f63ff"
    }
  },
  "teal": {
    "light": {
      "background": "#fafdfdff",
      "foreground": "#0c1917ff",
      "card": "#fafdfdff",
      "cardForeground": "#0c1917ff",
      "popover": "#fcffffff",
      "popoverForeground": "#0c1917ff",
      "primary": "#173430ff",
      "primaryForeground": "#f5faf9ff",
      "secondary": "#dbece9ff",
      "secondaryForeground": "#101e1cff",
      "muted": "#ebf4f3ff",
      "mutedForeground": "#51615fff",
      "accent": "#d2e6e3ff",
      "accentForeground": "#101e1cff",
      "destructive": "#e7000bff",
      "border": "#d1dedcff",
      "input": "#d1dedcff",
      "ring": "#008479ff"
    },
    "dark": {
      "background": "#081110ff",
      "foreground": "#eef3f2ff",
      "card": "#111d1cff",
      "cardForeground": "#eef3f2ff",
      "popover": "#111d1cff",
      "popoverForeground": "#eef3f2ff",
      "primary": "#cadcd9ff",
      "primaryForeground": "#101e1cff",
      "secondary": "#1f322fff",
      "secondaryForeground": "#eef3f2ff",
      "muted": "#1a2725ff",
      "mutedForeground": "#8b9d9aff",
      "accent": "#213835ff",
      "accentForeground": "#eef3f2ff",
      "destructive": "#ff6467ff",
      "border": "#ffffff1a",
      "input": "#ffffff26",
      "ring": "#319287ff"
    }
  },
  "blue": {
    "light": {
      "background": "#fbfdffff",
      "foreground": "#11161eff",
      "card": "#fbfdffff",
      "cardForeground": "#11161eff",
      "popover": "#fdffffff",
      "popoverForeground": "#11161eff",
      "primary": "#222f3fff",
      "primaryForeground": "#f6f9fcff",
      "secondary": "#e0e9f4ff",
      "secondaryForeground": "#141b24ff",
      "muted": "#edf2f9ff",
      "mutedForeground": "#565e69ff",
      "accent": "#d8e2f0ff",
      "accentForeground": "#141b24ff",
      "destructive": "#e7000bff",
      "border": "#d5dbe4ff",
      "input": "#d5dbe4ff",
      "ring": "#4773abff"
    },
    "dark": {
      "background": "#0b1015ff",
      "foreground": "#eff2f5ff",
      "card": "#151b23ff",
      "cardForeground": "#eff2f5ff",
      "popover": "#151b23ff",
      "popoverForeground": "#eff2f5ff",
      "primary": "#cfd8e5ff",
      "primaryForeground": "#141b24ff",
      "secondary": "#252f3aff",
      "secondaryForeground": "#eff2f5ff",
      "muted": "#1e252dff",
      "mutedForeground": "#9099a5ff",
      "accent": "#293442ff",
      "accentForeground": "#eff2f5ff",
      "destructive": "#ff6467ff",
      "border": "#ffffff1a",
      "input": "#ffffff26",
      "ring": "#5b82b5ff"
    }
  },
  "violet": {
    "light": {
      "background": "#fdfcffff",
      "foreground": "#17141dff",
      "card": "#fdfcffff",
      "cardForeground": "#17141dff",
      "popover": "#fffeffff",
      "popoverForeground": "#17141dff",
      "primary": "#302a3dff",
      "primaryForeground": "#f9f8fbff",
      "secondary": "#e9e5f2ff",
      "secondaryForeground": "#1c1923ff",
      "muted": "#f3f0f8ff",
      "mutedForeground": "#5f5b68ff",
      "accent": "#e3deeeff",
      "accentForeground": "#1c1923ff",
      "destructive": "#e7000bff",
      "border": "#dcd9e3ff",
      "input": "#dcd9e3ff",
      "ring": "#7b63a3ff"
    },
    "dark": {
      "background": "#100e15ff",
      "foreground": "#f2f1f5ff",
      "card": "#1c1922ff",
      "cardForeground": "#f2f1f5ff",
      "popover": "#1c1922ff",
      "popoverForeground": "#f2f1f5ff",
      "primary": "#d9d5e3ff",
      "primaryForeground": "#1c1923ff",
      "secondary": "#302b39ff",
      "secondaryForeground": "#f2f1f5ff",
      "muted": "#25222cff",
      "mutedForeground": "#9a96a3ff",
      "accent": "#352f40ff",
      "accentForeground": "#f2f1f5ff",
      "destructive": "#ff6467ff",
      "border": "#ffffff1a",
      "input": "#ffffff26",
      "ring": "#8874aeff"
    }
  },
  "rose": {
    "light": {
      "background": "#fffbfcff",
      "foreground": "#1d1316ff",
      "card": "#fffbfcff",
      "cardForeground": "#1d1316ff",
      "popover": "#fffefeff",
      "popoverForeground": "#1d1316ff",
      "primary": "#3c262fff",
      "primaryForeground": "#fbf7f8ff",
      "secondary": "#f2e3e8ff",
      "secondaryForeground": "#22171bff",
      "muted": "#f8eff2ff",
      "mutedForeground": "#67595eff",
      "accent": "#eedce2ff",
      "accentForeground": "#22171bff",
      "destructive": "#e7000bff",
      "border": "#e3d7dbff",
      "input": "#e3d7dbff",
      "ring": "#9f5774ff"
    },
    "dark": {
      "background": "#140d10ff",
      "foreground": "#f5f0f2ff",
      "card": "#22171bff",
      "cardForeground": "#f5f0f2ff",
      "popover": "#22171bff",
      "popoverForeground": "#f5f0f2ff",
      "primary": "#e3d2d8ff",
      "primaryForeground": "#22171bff",
      "secondary": "#38292eff",
      "secondaryForeground": "#f5f0f2ff",
      "muted": "#2b2024ff",
      "mutedForeground": "#a39399ff",
      "accent": "#3f2d34ff",
      "accentForeground": "#f5f0f2ff",
      "destructive": "#ff6467ff",
      "border": "#ffffff1a",
      "input": "#ffffff26",
      "ring": "#ab6983ff"
    }
  },
  "amber": {
    "light": {
      "background": "#fefcf9ff",
      "foreground": "#1b150dff",
      "card": "#fefcf9ff",
      "cardForeground": "#1b150dff",
      "popover": "#fffefcff",
      "popoverForeground": "#1b150dff",
      "primary": "#382b19ff",
      "primaryForeground": "#faf8f5ff",
      "secondary": "#efe6dbff",
      "secondaryForeground": "#201910ff",
      "muted": "#f6f1ebff",
      "mutedForeground": "#645c51ff",
      "accent": "#eae0d2ff",
      "accentForeground": "#201910ff",
      "destructive": "#e7000bff",
      "border": "#e0dad1ff",
      "input": "#e0dad1ff",
      "ring": "#936823ff"
    },
    "dark": {
      "background": "#130f09ff",
      "foreground": "#f4f1eeff",
      "card": "#201911ff",
      "cardForeground": "#f4f1eeff",
      "popover": "#201911ff",
      "popoverForeground": "#f4f1eeff",
      "primary": "#dfd6c9ff",
      "primaryForeground": "#201910ff",
      "secondary": "#352c20ff",
      "secondaryForeground": "#f4f1eeff",
      "muted": "#29231aff",
      "mutedForeground": "#a0978bff",
      "accent": "#3c3122ff",
      "accentForeground": "#f4f1eeff",
      "destructive": "#ff6467ff",
      "border": "#ffffff1a",
      "input": "#ffffff26",
      "ring": "#a0783eff"
    }
  },
  "neutral": {
    "light": {
      "background": "#fcfcfcff",
      "foreground": "#161616ff",
      "card": "#fcfcfcff",
      "cardForeground": "#161616ff",
      "popover": "#fefefeff",
      "popoverForeground": "#161616ff",
      "primary": "#2e2e2eff",
      "primaryForeground": "#f8f8f8ff",
      "secondary": "#e8e8e8ff",
      "secondaryForeground": "#1b1b1bff",
      "muted": "#f2f2f2ff",
      "mutedForeground": "#5d5d5dff",
      "accent": "#e1e1e1ff",
      "accentForeground": "#1b1b1bff",
      "destructive": "#e7000bff",
      "border": "#dbdbdbff",
      "input": "#dbdbdbff",
      "ring": "#717171ff"
    },
    "dark": {
      "background": "#0f0f0fff",
      "foreground": "#f2f2f2ff",
      "card": "#1b1b1bff",
      "cardForeground": "#f2f2f2ff",
      "popover": "#1b1b1bff",
      "popoverForeground": "#f2f2f2ff",
      "primary": "#d7d7d7ff",
      "primaryForeground": "#1b1b1bff",
      "secondary": "#2e2e2eff",
      "secondaryForeground": "#f2f2f2ff",
      "muted": "#242424ff",
      "mutedForeground": "#989898ff",
      "accent": "#333333ff",
      "accentForeground": "#f2f2f2ff",
      "destructive": "#ff6467ff",
      "border": "#ffffff1a",
      "input": "#ffffff26",
      "ring": "#808080ff"
    }
  }
};

export const accentSwatchesRgb: Record<AccentId, string> = {
  "olive": "#798940ff",
  "green": "#439458ff",
  "teal": "#1b9388ff",
  "blue": "#4081d2ff",
  "violet": "#8e6ac7ff",
  "rose": "#bf5884ff",
  "amber": "#bd821aff",
  "neutral": "#808080ff"
};
